const test = require("node:test");
const assert = require("node:assert/strict");
const mongoose = require("mongoose");
require("dotenv").config();
const Category = require("../models/Category"), Unit = require("../models/Unit"), Warehouse = require("../models/Warehouse"), RawMaterial = require("../models/RawMaterial"), Vendor = require("../models/Vendor"), PurchaseOrder = require("../models/PurchaseOrder"), GRN = require("../models/grn/grnModel"), PurchaseBill = require("../models/PurchaseBill"), AccountsPayable = require("../models/AccountsPayable"), SupplierPayment = require("../models/SupplierPayment"), Invoice = require("../models/Invoice"), Payment = require("../models/Payment");
const grnService = require("../services/grnService"), billService = require("../services/purchaseBillService"), paymentService = require("../services/supplierPaymentService"), apService = require("../services/accountsPayableService");
const vendorController = require("../controllers/vendor/vendorController");
const { protect, restrictTo } = require("../middleware/auth");
const uri = process.env.ACCOUNTS_PAYABLE_TEST_MONGODB_URI;

test("Accounts Payable and Supplier Payment routes require JWT and finance roles", async () => {
  const response = () => { const state = { status: 200 }; return { state, res: { status(code) { state.status = code; return this; }, json() { return this; } } }; };
  const missing = response(); await protect({ headers: {} }, missing.res, () => {}); assert.equal(missing.state.status, 401);
  const forbidden = response(); restrictTo("Super Admin", "Admin")({ user: { role: "Engineer" } }, forbidden.res, () => {}); assert.equal(forbidden.state.status, 403);
});

test("AP obligations and supplier payments are transactional, allocation-safe, reversible, and isolated", { skip: !uri }, async (t) => {
  await mongoose.connect(uri); t.after(async () => { await mongoose.connection.dropDatabase(); await mongoose.disconnect(); });
  await Promise.all([PurchaseOrder.init(), GRN.init(), PurchaseBill.init(), AccountsPayable.init(), SupplierPayment.init()]);
  const userId = new mongoose.Types.ObjectId(), category = await Category.create({ name: "AP Test" }), unit = await Unit.create({ name: "AP Unit", shortName: "APU" }), warehouse = await Warehouse.create({ warehouseCode: "AP-WH", warehouseName: "AP Warehouse", location: "Test" });
  const supplierA = await Vendor.create({ vendorCode: "AP-A", vendorName: "AP Supplier A", email: "ap-a@example.test" }), supplierB = await Vendor.create({ vendorCode: "AP-B", vendorName: "AP Supplier B", email: "ap-b@example.test" });
  const material = await RawMaterial.create({ materialCode: "AP-RM", materialName: "AP Canonical Material", category: category._id, unit: unit._id }); let serial = 0;
  const makeApproved = async (amount = 10000, supplier = supplierA, dueDate = new Date()) => {
    const identifier = ++serial;
    const po = await PurchaseOrder.create({ poNumber: `PO-AP-${identifier}`, vendorId: supplier._id, warehouseId: warehouse._id, status: "APPROVED", createdBy: userId, items: [{ itemType: "RawMaterial", item: material._id, itemCodeSnapshot: material.materialCode, itemNameSnapshot: material.materialName, quantity: 1, unitPrice: amount }] });
    const grn = await grnService.prepareDraft({ purchaseOrder: po._id, warehouse: warehouse._id, items: [{ poLineId: po.items[0]._id, quantityReceived: 1 }] }, userId); await grnService.post(grn._id, userId);
    const bill = await billService.createDraft({ purchaseOrder: po._id, supplier: supplier._id, supplierInvoiceNumber: `AP-INV-${identifier}`, invoiceDate: new Date(), dueDate, lines: [{ poLineId: po.items[0]._id, quantity: 1, unitPrice: amount }] }, userId); await billService.submit(bill._id, userId); const approved = await billService.approve(bill._id, userId); const ap = await AccountsPayable.findOne({ purchaseBill: bill._id }); return { po, bill: await PurchaseBill.findById(bill._id), approved, ap };
  };
  const pay = (supplier, allocations, totalAmount, suffix, method = "BANK_TRANSFER") => paymentService.create({ supplier: supplier._id, paymentDate: new Date(), paymentMethod: method, referenceNumber: method === "CASH" ? "" : `AP-REF-${suffix}`, totalAmount, allocations: allocations.map(([ap, amount]) => ({ accountsPayable: ap._id, amount })), idempotencyKey: `ap-key-${suffix}` }, userId);

  const full = await makeApproved(10000); assert(full.ap); assert.equal(full.ap.originalAmountMinor, 1000000); assert.equal(full.ap.outstandingAmountMinor, 1000000); assert.equal(full.ap.status, "OPEN"); assert.equal(full.bill.paymentStatus, "UNPAID");
  const fullPayment = await pay(supplierA, [[full.ap, 10000]], 10000, "full"); assert.equal(fullPayment.idempotent, false); let refreshed = await AccountsPayable.findById(full.ap._id); assert.equal(refreshed.status, "PAID"); assert.equal(refreshed.outstandingAmountMinor, 0); assert.equal((await PurchaseBill.findById(full.bill._id)).paymentStatus, "PAID");
  const reversed = await paymentService.reverse(fullPayment.payment._id, userId, "Bank entry correction"); assert.equal(reversed.alreadyReversed, false); refreshed = await AccountsPayable.findById(full.ap._id); assert.equal(refreshed.status, "OPEN"); assert.equal(refreshed.paidAmountMinor, 0); assert.equal((await PurchaseBill.findById(full.bill._id)).paymentStatus, "UNPAID"); const doubleReversal = await paymentService.reverse(fullPayment.payment._id, userId, "Again"); assert.equal(doubleReversal.alreadyReversed, true); assert.equal((await AccountsPayable.findById(full.ap._id)).outstandingAmountMinor, 1000000);

  const partial = await makeApproved(10000); await pay(supplierA, [[partial.ap, 4000]], 4000, "partial-one"); refreshed = await AccountsPayable.findById(partial.ap._id); assert.equal(refreshed.status, "PARTIALLY_PAID"); assert.equal(refreshed.paidAmountMinor, 400000); assert.equal(refreshed.outstandingAmountMinor, 600000); await pay(supplierA, [[refreshed, 6000]], 6000, "partial-two"); assert.equal((await AccountsPayable.findById(partial.ap._id)).status, "PAID"); await assert.rejects(pay(supplierA, [[await AccountsPayable.findById(partial.ap._id), 0.01]], 0.01, "overpaid"), /no outstanding/); assert.equal(await SupplierPayment.countDocuments({ "allocations.accountsPayable": partial.ap._id }), 2);

  const multiA = await makeApproved(4000), multiB = await makeApproved(6000), foreign = await makeApproved(1000, supplierB); const multi = await pay(supplierA, [[multiA.ap, 4000], [multiB.ap, 6000]], 10000, "multi"); assert.equal(multi.payment.allocations.length, 2); assert.equal((await AccountsPayable.findById(multiA.ap._id)).status, "PAID"); assert.equal((await AccountsPayable.findById(multiB.ap._id)).status, "PAID"); await assert.rejects(pay(supplierA, [[foreign.ap, 1]], 1, "foreign"), /selected supplier/); assert.equal((await AccountsPayable.findById(foreign.ap._id)).outstandingAmountMinor, 100000);

  const duplicate = await makeApproved(500); const first = await pay(supplierA, [[duplicate.ap, 500]], 500, "idempotent"); const replay = await paymentService.create({ supplier: supplierA._id, paymentDate: new Date(), paymentMethod: "BANK_TRANSFER", referenceNumber: "AP-REF-idempotent", totalAmount: 500, allocations: [{ accountsPayable: duplicate.ap._id, amount: 500 }], idempotencyKey: "ap-key-idempotent" }, userId); assert.equal(replay.idempotent, true); assert.equal(String(replay.payment._id), String(first.payment._id)); assert.equal(await SupplierPayment.countDocuments({ idempotencyKey: "ap-key-idempotent" }), 1); const duplicateRef = await makeApproved(500); await assert.rejects(paymentService.create({ supplier: supplierA._id, paymentDate: new Date(), paymentMethod: "BANK_TRANSFER", referenceNumber: "AP-REF-idempotent", totalAmount: 500, allocations: [{ accountsPayable: duplicateRef.ap._id, amount: 500 }], idempotencyKey: "same-reference-different-key" }, userId), (error) => error.code === 11000); const otherSupplierSameRef = await makeApproved(500, supplierB); assert((await paymentService.create({ supplier: supplierB._id, paymentDate: new Date(), paymentMethod: "BANK_TRANSFER", referenceNumber: "AP-REF-idempotent", totalAmount: 500, allocations: [{ accountsPayable: otherSupplierSameRef.ap._id, amount: 500 }], idempotencyKey: "other-supplier-same-reference" }, userId)).payment);

  const concurrent = await makeApproved(5000); const concurrentResults = await Promise.allSettled([pay(supplierA, [[concurrent.ap, 5000]], 5000, "concurrent-a"), pay(supplierA, [[concurrent.ap, 5000]], 5000, "concurrent-b")]); assert.equal(concurrentResults.filter((result) => result.status === "fulfilled").length, 1); refreshed = await AccountsPayable.findById(concurrent.ap._id); assert.equal(refreshed.outstandingAmountMinor, 0); assert.equal(refreshed.paidAmountMinor, 500000);

  const rollbackA = await makeApproved(1000), rollbackB = await makeApproved(1000); const originalSave = AccountsPayable.prototype.save; let updates = 0; AccountsPayable.prototype.save = async function forcedFailure(options) { if (this.isModified("paidAmountMinor") && ++updates === 2) throw new Error("forced AP allocation failure"); return originalSave.call(this, options); }; try { await assert.rejects(pay(supplierA, [[rollbackA.ap, 1000], [rollbackB.ap, 1000]], 2000, "rollback"), /forced AP allocation failure/); } finally { AccountsPayable.prototype.save = originalSave; } assert.equal((await AccountsPayable.findById(rollbackA.ap._id)).paidAmountMinor, 0); assert.equal((await AccountsPayable.findById(rollbackB.ap._id)).paidAmountMinor, 0); assert.equal(await SupplierPayment.countDocuments({ idempotencyKey: "ap-key-rollback" }), 0);

  const draftPO = await PurchaseOrder.create({ poNumber: `PO-AP-DRAFT-${++serial}`, vendorId: supplierA._id, warehouseId: warehouse._id, status: "APPROVED", createdBy: userId, items: [{ itemType: "RawMaterial", item: material._id, quantity: 1, unitPrice: 10 }] }); const draftBill = await billService.createDraft({ purchaseOrder: draftPO._id, supplier: supplierA._id, supplierInvoiceNumber: "AP-DRAFT", invoiceDate: new Date(), lines: [{ poLineId: draftPO.items[0]._id, quantity: 1, unitPrice: 10 }] }, userId); const invalidAp = await AccountsPayable.create({ supplier: supplierA._id, purchaseBill: draftBill._id, originalAmountMinor: 1000, outstandingAmountMinor: 1000, currency: "INR" }); for (const status of ["DRAFT", "SUBMITTED", "REJECTED", "CANCELLED"]) { await PurchaseBill.updateOne({ _id: draftBill._id }, { $set: { status } }); await assert.rejects(pay(supplierA, [[invalidAp, 10]], 10, `invalid-${status}`), /Only approved/); }

  const deleteResponse = { statusCode: 200 }; await vendorController.deleteVendor({ params: { id: supplierA._id } }, { status(code) { deleteResponse.statusCode = code; return this; }, json(body) { deleteResponse.body = body; return this; } }); assert.equal(deleteResponse.statusCode, 409); assert.match(deleteResponse.body.message, /cannot be deleted/);

  const backfillTarget = await makeApproved(250); await AccountsPayable.deleteOne({ _id: backfillTarget.ap._id }); await PurchaseBill.updateOne({ _id: backfillTarget.bill._id }, { $set: { accountsPayable: null, paymentStatus: "UNPAID", paidAmountMinor: 0, outstandingAmountMinor: 0 } }); const dryRun = await apService.backfill({ apply: false, actor: userId }); assert(dryRun.wouldCreate.includes(String(backfillTarget.bill._id))); assert.equal(await AccountsPayable.countDocuments({ purchaseBill: backfillTarget.bill._id }), 0); await apService.backfill({ apply: true, actor: userId }); await apService.backfill({ apply: true, actor: userId }); assert.equal(await AccountsPayable.countDocuments({ purchaseBill: backfillTarget.bill._id }), 1);

  const now = new Date(); const agingAPs = await Promise.all([0, 10, 45, 75, 120].map(async (days, index) => { const item = await makeApproved(100 + index); const due = new Date(now); due.setDate(due.getDate() - days); await AccountsPayable.updateOne({ _id: item.ap._id }, { $set: { dueDate: due } }); return item.ap._id; })); const aging = await apService.aging(); assert(aging.data.some((row) => String(row._id) === String(agingAPs[0]) && row.agingBucket === "CURRENT")); assert(aging.data.some((row) => String(row._id) === String(agingAPs[1]) && row.agingBucket === "1_30")); assert(aging.data.some((row) => String(row._id) === String(agingAPs[2]) && row.agingBucket === "31_60")); assert(aging.data.some((row) => String(row._id) === String(agingAPs[3]) && row.agingBucket === "61_90")); assert(aging.data.some((row) => String(row._id) === String(agingAPs[4]) && row.agingBucket === "90_PLUS")); assert(!aging.data.some((row) => String(row._id) === String(multiA.ap)));
  assert.equal(await Invoice.countDocuments(), 0); assert.equal(await Payment.countDocuments(), 0);
});
