const test = require("node:test");
const assert = require("node:assert/strict");
const mongoose = require("mongoose");
require("dotenv").config();
const Category = require("../models/Category"), Unit = require("../models/Unit"), Warehouse = require("../models/Warehouse"), Product = require("../models/Product"), RawMaterial = require("../models/RawMaterial"), Component = require("../models/Component");
const InventoryBalance = require("../models/InventoryBalance"), InventoryTransaction = require("../models/InventoryTransaction"), InventoryAudit = require("../models/InventoryAudit");
const service = require("../services/canonicalInventoryService"), controller = require("../controllers/inventoryController");
const { protect, restrictTo } = require("../middleware/auth");
const uri = process.env.TEST_MONGODB_URI, enabled = Boolean(uri && /inventory-phase3-test/i.test(uri));
const invoke = async (handler, query = {}) => { const result = { statusCode: 200 }; const res = { status(code) { result.statusCode = code; return this; }, json(payload) { result.payload = payload; return this; } }; await handler({ query }, res); return result; };

test("inventory authorization rejects missing credentials and unauthorized roles", async () => {
  const response = () => { const result = { statusCode: 200 }; return { result, res: { status(code) { result.statusCode = code; return this; }, json() { return this; } } }; };
  const missing = response(); await protect({ headers: {} }, missing.res, () => {}); assert.equal(missing.result.statusCode, 401);
  const forbidden = response(); restrictTo("Admin")({ user: { role: "Engineer" } }, forbidden.res, () => {}); assert.equal(forbidden.result.statusCode, 403);
});

test("atomic polymorphic inventory lifecycle", { skip: !enabled }, async (t) => {
  await mongoose.connect(uri); assert.match(mongoose.connection.name, /inventory-phase3-test/i);
  t.after(async () => { await mongoose.connection.dropDatabase(); await mongoose.disconnect(); });
  await Promise.all([InventoryBalance.init(), InventoryTransaction.init(), InventoryAudit.init()]);
  const userId = new mongoose.Types.ObjectId(), category = await Category.create({ name: "Inventory Test" }), unit = await Unit.create({ name: "Inventory Unit", shortName: "IU" });
  const [w1, w2] = await Warehouse.create([{ warehouseCode: "INV-A", warehouseName: "A", location: "Test" }, { warehouseCode: "INV-B", warehouseName: "B", location: "Test" }]);
  const product = await Product.create({ productCode: "INV-P", productName: "Product", productType: "Finished Product", category: category._id, unit: unit._id, reorderLevel: 5 });
  const raw = await RawMaterial.create({ materialCode: "INV-R", materialName: "Raw", category: category._id, unit: unit._id, reorderLevel: 3 });
  const component = await Component.create({ componentCode: "INV-C", componentName: "Component", category: category._id, unit: unit._id, reorderLevel: 2 });
  const base = { itemType: "Product", item: product._id, warehouse: w1._id, quantity: 10, reason: "Opening test" };
  assert.equal((await service.stockIn(base, userId)).balance.quantity, 10);
  assert.equal((await service.stockIn({ ...base, quantity: 5 }, userId)).balance.quantity, 15);
  await service.stockIn({ itemType: "RawMaterial", item: raw._id, warehouse: w1._id, quantity: 4 }, userId);
  await service.stockIn({ itemType: "Component", item: component._id, warehouse: w2._id, quantity: 3 }, userId);
  assert.equal(await InventoryBalance.countDocuments(), 3);
  await assert.rejects(service.stockIn({ ...base, item: new mongoose.Types.ObjectId() }, userId), /not found/);
  await assert.rejects(service.stockIn({ ...base, warehouse: new mongoose.Types.ObjectId() }, userId), /not found/);
  await assert.rejects(service.stockIn({ ...base, quantity: 0 }, userId), /greater than zero/);
  assert.equal((await service.stockOut({ ...base, quantity: 4 }, userId)).balance.quantity, 11);
  await assert.rejects(service.stockOut({ ...base, quantity: 99 }, userId), /Insufficient/);
  assert.equal((await InventoryBalance.findOne({ item: product._id, warehouse: w1._id })).quantity, 11);
  const moved = await service.transfer({ itemType: "Product", item: product._id, sourceWarehouse: w1._id.toString(), destinationWarehouse: w2._id.toString(), quantity: 3 }, userId);
  assert.equal(moved.transactions.length, 2); assert.equal(new Set(moved.transactions.map((row) => row.batchId)).size, 1);
  assert.equal((await InventoryBalance.findOne({ item: product._id, warehouse: w1._id })).quantity, 8); assert.equal((await InventoryBalance.findOne({ item: product._id, warehouse: w2._id })).quantity, 3);
  await assert.rejects(service.transfer({ itemType: "Product", item: product._id, sourceWarehouse: w1._id.toString(), destinationWarehouse: w1._id.toString(), quantity: 1 }, userId), /different warehouses/);
  await assert.rejects(service.transfer({ itemType: "Product", item: product._id, sourceWarehouse: w1._id.toString(), destinationWarehouse: w2._id.toString(), quantity: 100 }, userId), /Insufficient/);
  assert.equal((await InventoryBalance.findOne({ item: product._id, warehouse: w2._id })).quantity, 3);
  const equal = await service.audit({ itemType: "Product", item: product._id, warehouse: w2._id, physicalQuantity: 3 }, userId); assert.equal(equal.audit.difference, 0); assert.equal(equal.transaction, null);
  assert.equal((await service.audit({ itemType: "Product", item: product._id, warehouse: w2._id, physicalQuantity: 7 }, userId)).transaction.movementType, "AdjustmentIncrease");
  assert.equal((await service.audit({ itemType: "Product", item: product._id, warehouse: w2._id, physicalQuantity: 2 }, userId)).transaction.movementType, "AdjustmentDecrease");
  assert.equal(await InventoryAudit.countDocuments(), 3);
  product.reorderLevel = 10; await product.save();
  raw.reorderLevel = 5; await raw.save();
  const zeroItem = await Component.create({ componentCode: "INV-Z", componentName: "Zero Component", category: category._id, unit: unit._id, reorderLevel: 1 });
  const alerts = await invoke(controller.getReorderAlerts); assert.equal(alerts.statusCode, 200);
  assert.ok(alerts.payload.data.some((row) => String(row.item._id) === String(product._id) && row.quantity === 10));
  assert.ok(alerts.payload.data.some((row) => String(row.item._id) === String(raw._id) && row.quantity === 4));
  assert.ok(alerts.payload.data.some((row) => String(row.item._id) === String(zeroItem._id) && row.quantity === 0));
  assert.ok(!alerts.payload.data.some((row) => String(row.item._id) === String(component._id)));
  const beforeConcurrency = await InventoryBalance.findOne({ item: product._id, warehouse: w1._id }); beforeConcurrency.quantity = 10; await beforeConcurrency.save();
  const attempts = await Promise.allSettled([service.stockOut({ ...base, quantity: 7 }, userId), service.stockOut({ ...base, quantity: 7 }, userId)]);
  assert.equal(attempts.filter((entry) => entry.status === "fulfilled").length, 1); assert.equal((await InventoryBalance.findById(beforeConcurrency._id)).quantity, 3);
  assert.equal(await InventoryBalance.countDocuments({ itemType: "Product", item: product._id, warehouse: w1._id }), 1);
});
