const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs"), os = require("os"), path = require("path");
const mongoose = require("mongoose");
require("dotenv").config();
const Category = require("../models/Category"), Unit = require("../models/Unit"), Product = require("../models/Product"), RawMaterial = require("../models/RawMaterial"), Component = require("../models/Component"), Vendor = require("../models/Vendor"), PurchaseRequisition = require("../models/PurchaseRequisition");
const migration = require("../services/procurementMigrationService"), procurement = require("../services/procurementIdentityService");
const uri = process.env.MIGRATION_TEST_MONGODB_URI;

test("legacy Material writes fail closed", () => { const block = require("../middleware/blockLegacyMaterialWrites"), result = { statusCode: 200 }; block({}, { status(code) { result.statusCode = code; return this; }, json(payload) { result.payload = payload; return this; } }); assert.equal(result.statusCode, 410); assert.match(result.payload.message, /canonical itemType/); });

test("legacy procurement migration is dry-run-first, transactional, idempotent, and reversible", { skip: !uri }, async (t) => {
  await mongoose.connect(uri); const db = mongoose.connection.db, output = fs.mkdtempSync(path.join(os.tmpdir(), "proc-migration-")); t.after(async () => { fs.rmSync(output, { recursive: true, force: true }); await mongoose.connection.dropDatabase(); await mongoose.disconnect(); });
  const category = await Category.create({ name: "Migration" }), unit = await Unit.create({ name: "Each", shortName: "EA" });
  const raw = await RawMaterial.create({ materialCode: "LEG-RM-1", materialName: "Legacy Steel", category: category._id, unit: unit._id }), product = await Product.create({ productCode: "LEG-P-1", productName: "Legacy Product", productType: "Finished Product", category: category._id, unit: unit._id });
  await Product.create({ productCode: "DUP-CODE", productName: "Duplicate Product", productType: "Finished Product", category: category._id, unit: unit._id }); await Component.create({ componentCode: "DUP-CODE", componentName: "Duplicate Component", category: category._id, unit: unit._id });
  const ids = { safe: new mongoose.Types.ObjectId(), manual: new mongoose.Types.ObjectId(), ambiguous: new mongoose.Types.ObjectId(), unresolved: new mongoose.Types.ObjectId() };
  await db.collection("materials").insertMany([{ _id: ids.safe, materialCode: "LEG-RM-1", materialName: "Legacy Steel" }, { _id: ids.manual, materialCode: "NO-AUTO" }, { _id: ids.ambiguous, materialCode: "DUP-CODE" }, { _id: ids.unresolved, materialCode: "NOT-FOUND" }]);
  const userId = new mongoose.Types.ObjectId(), prId = new mongoose.Types.ObjectId(), rfqId = new mongoose.Types.ObjectId(), poId = new mongoose.Types.ObjectId(), eligiblePR = new mongoose.Types.ObjectId();
  await db.collection("purchaserequests").insertMany([{ _id: prId, materialId: ids.safe }, { _id: new mongoose.Types.ObjectId(), materialId: ids.ambiguous }, { _id: new mongoose.Types.ObjectId(), materialId: ids.unresolved }, { _id: new mongoose.Types.ObjectId(), materialId: raw._id }, { _id: new mongoose.Types.ObjectId(), materialId: ids.safe, itemType: "Product", item: product._id }]);
  await db.collection("rfqs").insertOne({ _id: rfqId, sourceRequisition: prId, materialId: ids.safe }); await db.collection("purchaseorders").insertOne({ _id: poId, sourceRFQ: rfqId, materialId: ids.safe });
  await db.collection("purchaserequisitions").insertOne({ _id: eligiblePR, requisitionNo: "PR-LEGACY-MIG", department: "Production", requestedBy: userId, status: "APPROVED", items: [{ _id: new mongoose.Types.ObjectId(), materialId: ids.safe, requestedQuantity: 5, orderedQuantity: 0 }], createdAt: new Date(), updatedAt: new Date() });
  await db.collection("vendormaterials").insertOne({ _id: new mongoose.Types.ObjectId(), vendorId: new mongoose.Types.ObjectId(), materialId: ids.manual, price: 1 });
  const overrideFile = path.join(output, "overrides.json"); fs.writeFileSync(overrideFile, JSON.stringify([{ legacyMaterialId: String(ids.manual), itemType: "RawMaterial", item: String(raw._id), reason: "Reviewed test mapping" }]));
  const before = JSON.stringify(await db.collection("purchaserequests").find({}).sort({ _id: 1 }).toArray()); const plan = await migration.survey(db, { mappingFile: overrideFile }); const report = migration.writeReports(plan, output); const after = JSON.stringify(await db.collection("purchaserequests").find({}).sort({ _id: 1 }).toArray());
  assert.equal(before, after); assert.ok(report.mappings.some((row) => row.confidence === "EXACT_CODE")); assert.ok(report.mappings.some((row) => row.confidence === "EXPLICIT_MAPPING")); assert.ok(report.ambiguous.some((row) => row.status === "AMBIGUOUS")); assert.ok(report.unresolved.some((row) => row.status === "UNRESOLVED")); assert.ok(report.conflicts.some((row) => row.status === "CONFLICT")); for (const file of ["summary.json", "mappings.json", "ambiguous.json", "unresolved.json", "conflicts.json", "affected-records.json"]) assert.ok(fs.existsSync(path.join(output, file)));
  await assert.rejects(migration.apply(db, plan, { outputDir: output, apply: false }), /requires/);
  const applied = await migration.apply(db, plan, { outputDir: output, apply: true, confirm: "MIGRATE_LEGACY_IDENTITY", batchSize: 1 }); assert.ok(fs.existsSync(applied.backupFile));
  const migratedPR = await db.collection("purchaserequisitions").findOne({ _id: eligiblePR }); assert.equal(migratedPR.items[0].itemType, "RawMaterial"); assert.equal(String(migratedPR.items[0].item), String(raw._id)); assert.equal(String(migratedPR.items[0].materialId), String(ids.safe)); assert.equal(migratedPR.items[0].identityMigration.version, 1);
  const vendor = await Vendor.create({ vendorCode: "MIG-V", vendorName: "Migration Vendor", email: "migration@example.test" }); const converted = await procurement.createRFQFromPR(eligiblePR, { vendorIds: [vendor._id] }, userId); assert.equal(converted.rfq.items[0].itemType, "RawMaterial");
  const firstMetadata = (await db.collection("purchaserequests").findOne({ _id: prId })).identityMigration.migratedAt; const secondPlan = await migration.survey(db, { mappingFile: overrideFile }); assert.ok(secondPlan.records.some((row) => row.status === "ALREADY_MIGRATED")); const reapplied = await migration.apply(db, secondPlan, { outputDir: output, apply: true, confirm: "MIGRATE_LEGACY_IDENTITY", batchSize: 1 }); assert.equal(reapplied.migrated.length, 0); assert.deepEqual((await db.collection("purchaserequests").findOne({ _id: prId })).identityMigration.migratedAt, firstMetadata);
  const verification = await migration.verify(db); assert.equal(verification.invalid.length, 0);
  await assert.rejects(migration.rollback(db, applied.backupFile, { apply: false }), /requires/); const rolled = await migration.rollback(db, applied.backupFile, { apply: true, confirm: "ROLLBACK_LEGACY_IDENTITY", batchSize: 1 }); assert.ok(rolled.restored > 0); const restored = await db.collection("purchaserequests").findOne({ _id: prId }); assert.equal(restored.itemType, undefined); assert.equal(restored.item, undefined); assert.equal(String(restored.materialId), String(ids.safe));

  for (const name of ["purchaserequests", "rfqs", "purchaseorders", "purchaserequisitions", "vendormaterials"]) await db.collection(name).deleteMany({});
  const rollbackA = new mongoose.Types.ObjectId(), rollbackB = new mongoose.Types.ObjectId(); await db.collection("purchaserequests").insertOne({ _id: rollbackA, materialId: ids.safe }); await db.collection("rfqs").insertOne({ _id: rollbackB, sourceRequisition: rollbackA, materialId: ids.safe }); const rollbackPlan = await migration.survey(db, { mappingFile: overrideFile }); await db.collection("rfqs").deleteOne({ _id: rollbackB }); await assert.rejects(migration.apply(db, rollbackPlan, { outputDir: output, apply: true, confirm: "MIGRATE_LEGACY_IDENTITY", batchSize: 10 }), /disappeared/); assert.equal((await db.collection("purchaserequests").findOne({ _id: rollbackA })).itemType, undefined);

  await db.collection("purchaserequests").deleteMany({}); await db.collection("rfqs").deleteMany({}); const conflictPR = new mongoose.Types.ObjectId(); await db.collection("purchaserequests").insertOne({ _id: conflictPR, materialId: raw._id }); await db.collection("rfqs").insertOne({ _id: new mongoose.Types.ObjectId(), sourceRequisition: conflictPR, materialId: product._id }); const conflictPlan = await migration.survey(db); assert.ok(conflictPlan.records.every((row) => row.status === "CHAIN_CONFLICT"));
});
