const mongoose = require("mongoose");
const AccountsPayable = require("../models/AccountsPayable");
const PurchaseBill = require("../models/PurchaseBill");

const fail = (message, statusCode = 400) => Object.assign(new Error(message), { statusCode });
const startOfBusinessDay = (value = new Date()) => { const date = new Date(value); return new Date(date.getFullYear(), date.getMonth(), date.getDate()); };
const agingFor = (ap, now = new Date()) => {
  const outstanding = Number(ap.outstandingAmountMinor || 0); if (!outstanding || !ap.dueDate) return { overdue: false, daysOverdue: 0, agingBucket: "CURRENT" };
  const daysOverdue = Math.max(0, Math.floor((startOfBusinessDay(now) - startOfBusinessDay(ap.dueDate)) / 86400000));
  if (!daysOverdue) return { overdue: false, daysOverdue: 0, agingBucket: "CURRENT" };
  return { overdue: true, daysOverdue, agingBucket: daysOverdue <= 30 ? "1_30" : daysOverdue <= 60 ? "31_60" : daysOverdue <= 90 ? "61_90" : "90_PLUS" };
};
const decorate = (document, now) => { const value = document.toObject ? document.toObject() : document; return { ...value, ...agingFor(value, now) }; };
const ensureForApprovedBill = async (bill, actor, session) => {
  if (bill.status !== "APPROVED") throw fail("Only an approved Purchase Bill can open Accounts Payable", 409);
  let payable = await AccountsPayable.findOne({ purchaseBill: bill._id }).session(session || null);
  if (!payable) {
    const created = await AccountsPayable.create([{ supplier: bill.supplier, purchaseBill: bill._id, originalAmountMinor: bill.grandTotalMinor, paidAmountMinor: 0, outstandingAmountMinor: bill.grandTotalMinor, currency: bill.currency, dueDate: bill.dueDate, status: bill.grandTotalMinor === 0 ? "PAID" : "OPEN", openedAt: new Date(), closedAt: bill.grandTotalMinor === 0 ? new Date() : null, auditTrail: [{ action: "OPENED", actor, amountMinor: bill.grandTotalMinor }] }], { session }); payable = created[0];
  } else if (String(payable.supplier) !== String(bill.supplier) || payable.originalAmountMinor !== bill.grandTotalMinor || payable.currency !== bill.currency) throw fail("Existing Accounts Payable does not match the approved Purchase Bill", 409);
  bill.accountsPayable = payable._id; bill.paidAmountMinor = payable.paidAmountMinor; bill.outstandingAmountMinor = payable.outstandingAmountMinor; bill.paymentStatus = payable.outstandingAmountMinor === 0 ? "PAID" : payable.paidAmountMinor > 0 ? "PARTIALLY_PAID" : "UNPAID";
  return payable;
};
const list = async (query = {}) => {
  const page = Math.max(1, Number(query.page) || 1), limit = Math.min(100, Math.max(1, Number(query.limit) || 10)), filter = {};
  if (query.supplier && mongoose.isValidObjectId(query.supplier)) filter.supplier = query.supplier; if (query.status) filter.status = query.status;
  if (query.dueFrom || query.dueTo) { filter.dueDate = {}; if (query.dueFrom) filter.dueDate.$gte = new Date(query.dueFrom); if (query.dueTo) { const to = new Date(query.dueTo); to.setHours(23, 59, 59, 999); filter.dueDate.$lte = to; } }
  if (query.search) { const bills = await PurchaseBill.find({ $or: [{ billNumber: { $regex: query.search, $options: "i" } }, { supplierInvoiceNumber: { $regex: query.search, $options: "i" } }] }).distinct("_id"); filter.purchaseBill = { $in: bills }; }
  if (query.paymentStatus === "UNPAID") { filter.paidAmountMinor = 0; filter.outstandingAmountMinor = { $gt: 0 }; } else if (query.paymentStatus === "PARTIALLY_PAID") { filter.paidAmountMinor = { $gt: 0 }; filter.outstandingAmountMinor = { $gt: 0 }; } else if (query.paymentStatus === "PAID") filter.outstandingAmountMinor = 0;
  if (String(query.overdue) === "true") { filter.outstandingAmountMinor = { $gt: 0 }; filter.dueDate = { ...(filter.dueDate || {}), $lt: startOfBusinessDay() }; }
  const [rows, total] = await Promise.all([AccountsPayable.find(filter).populate("supplier", "vendorCode vendorName email").populate("purchaseBill", "billNumber supplierInvoiceNumber purchaseOrder status paymentStatus").sort({ dueDate: 1, createdAt: -1 }).skip((page - 1) * limit).limit(limit), AccountsPayable.countDocuments(filter)]);
  return { data: rows.map((row) => decorate(row)), pagination: { page, limit, total, pages: Math.ceil(total / limit) } };
};
const detail = async (id) => { if (!mongoose.isValidObjectId(id)) throw fail("Invalid Accounts Payable ID"); const ap = await AccountsPayable.findById(id).populate("supplier", "vendorCode vendorName email phone paymentTerms").populate({ path: "purchaseBill", populate: { path: "purchaseOrder", select: "poNumber" } }).populate("auditTrail.actor", "name email").populate("auditTrail.payment", "paymentNumber paymentDate status"); if (!ap) throw fail("Accounts Payable not found", 404); return decorate(ap); };
const aging = async (query = {}) => { const filter = { outstandingAmountMinor: { $gt: 0 }, status: { $ne: "CANCELLED" } }; if (query.supplier && mongoose.isValidObjectId(query.supplier)) filter.supplier = query.supplier; const rows = await AccountsPayable.find(filter).populate("supplier", "vendorCode vendorName").populate("purchaseBill", "billNumber supplierInvoiceNumber"); const buckets = { CURRENT: 0, "1_30": 0, "31_60": 0, "61_90": 0, "90_PLUS": 0 }, suppliers = new Map(); const data = rows.map((row) => { const value = decorate(row); buckets[value.agingBucket] += value.outstandingAmountMinor; const key = String(value.supplier?._id || value.supplier); const current = suppliers.get(key) || { supplier: value.supplier, outstandingAmountMinor: 0 }; current.outstandingAmountMinor += value.outstandingAmountMinor; suppliers.set(key, current); return value; }); return { buckets, supplierTotals: [...suppliers.values()], data } };
const summary = async () => { const now = startOfBusinessDay(), seven = new Date(now); seven.setDate(seven.getDate() + 7); const thirty = new Date(now); thirty.setDate(thirty.getDate() + 30); const rows = await AccountsPayable.find({ outstandingAmountMinor: { $gt: 0 }, status: { $ne: "CANCELLED" } }).populate("supplier", "vendorCode vendorName").lean(); const totalOutstandingMinor = rows.reduce((sum, row) => sum + row.outstandingAmountMinor, 0), overdueTotalMinor = rows.filter((row) => row.dueDate && startOfBusinessDay(row.dueDate) < now).reduce((sum, row) => sum + row.outstandingAmountMinor, 0); const suppliers = new Map(); for (const row of rows) { const key = String(row.supplier?._id || row.supplier); const current = suppliers.get(key) || { supplier: row.supplier, outstandingAmountMinor: 0 }; current.outstandingAmountMinor += row.outstandingAmountMinor; suppliers.set(key, current); } return { totalOutstandingMinor, currentTotalMinor: totalOutstandingMinor - overdueTotalMinor, overdueTotalMinor, dueWithin7DaysMinor: rows.filter((row) => row.dueDate && startOfBusinessDay(row.dueDate) >= now && startOfBusinessDay(row.dueDate) <= seven).reduce((sum, row) => sum + row.outstandingAmountMinor, 0), dueWithin30DaysMinor: rows.filter((row) => row.dueDate && startOfBusinessDay(row.dueDate) >= now && startOfBusinessDay(row.dueDate) <= thirty).reduce((sum, row) => sum + row.outstandingAmountMinor, 0), supplierTotals: [...suppliers.values()] }; };
const backfill = async ({ apply = false, actor }) => { const bills = await PurchaseBill.find({ status: "APPROVED" }).select("_id supplier grandTotalMinor currency dueDate accountsPayable paymentStatus paidAmountMinor outstandingAmountMinor"); const existing = new Set((await AccountsPayable.find({ purchaseBill: { $in: bills.map((b) => b._id) } }).distinct("purchaseBill")).map(String)); const missing = bills.filter((bill) => !existing.has(String(bill._id))); if (!apply) return { dryRun: true, approvedBills: bills.length, missing: missing.length, wouldCreate: missing.map((bill) => String(bill._id)) }; for (const candidate of missing) { const session = await mongoose.startSession(); try { await session.withTransaction(async () => { const bill = await PurchaseBill.findOne({ _id: candidate._id, status: "APPROVED" }).session(session); if (!bill) return; await ensureForApprovedBill(bill, actor, session); await bill.save({ session }); }); } finally { await session.endSession(); } } return { dryRun: false, approvedBills: bills.length, created: missing.length }; };

module.exports = { fail, startOfBusinessDay, agingFor, decorate, ensureForApprovedBill, list, detail, aging, summary, backfill };
