import { useEffect, useState } from "react";
import { listMasterRecords } from "../../services/productMasterService";

const resource = { Product: "products", RawMaterial: "raw-materials", Component: "components" };
const display = (item) => `${item.productCode || item.materialCode || item.componentCode} — ${item.productName || item.materialName || item.componentName}`;
const CreatePurchaseRequisitionModal = ({ open, onClose, onSubmit }) => {
  const [itemType, setItemType] = useState("RawMaterial"), [masters, setMasters] = useState([]), [form, setForm] = useState({ item: "", requestedQuantity: "", department: "", requiredDate: "", priority: "MEDIUM", estimatedUnitPrice: "", justification: "" });
  useEffect(() => { if (open) listMasterRecords(resource[itemType], { limit: 200, status: "Active" }).then((res) => setMasters(res.data || [])).catch(() => setMasters([])); }, [open, itemType]);
  if (!open) return null;
  const submit = (event) => { event.preventDefault(); onSubmit({ department: form.department, requiredDate: form.requiredDate, priority: form.priority, justification: form.justification, items: [{ itemType, item: form.item, requestedQuantity: Number(form.requestedQuantity), estimatedUnitPrice: Number(form.estimatedUnitPrice || 0), requiredBy: form.requiredDate }] }); };
  return <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4"><form onSubmit={submit} className="bg-base-100 p-6 rounded-xl shadow-xl w-full max-w-2xl space-y-4"><h2 className="text-xl font-bold">Create Purchase Requisition</h2><div className="grid md:grid-cols-2 gap-4"><label className="form-control"><span className="label-text">Item type</span><select className="select select-bordered" value={itemType} onChange={(e) => { setItemType(e.target.value); setForm({ ...form, item: "" }); }}><option value="Product">Product</option><option value="RawMaterial">Raw Material</option><option value="Component">Component</option></select></label><label className="form-control"><span className="label-text">Canonical item</span><select className="select select-bordered" value={form.item} onChange={(e) => setForm({ ...form, item: e.target.value })} required><option value="">Select item</option>{masters.map((item) => <option key={item._id} value={item._id}>{display(item)}</option>)}</select></label><input className="input input-bordered" placeholder="Requested quantity" type="number" min="0" step="any" value={form.requestedQuantity} onChange={(e) => setForm({ ...form, requestedQuantity: e.target.value })} required/><input className="input input-bordered" placeholder="Estimated unit price" type="number" min="0" step="any" value={form.estimatedUnitPrice} onChange={(e) => setForm({ ...form, estimatedUnitPrice: e.target.value })}/><input className="input input-bordered" placeholder="Department" value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} required/><input className="input input-bordered" type="date" value={form.requiredDate} onChange={(e) => setForm({ ...form, requiredDate: e.target.value })}/><select className="select select-bordered" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></div><textarea className="textarea textarea-bordered w-full" placeholder="Justification" value={form.justification} onChange={(e) => setForm({ ...form, justification: e.target.value })}/><div className="flex gap-3 justify-end"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn btn-primary">Save PR</button></div></form></div>;
};
export default CreatePurchaseRequisitionModal;
