import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { createPR, getAllPRs, updatePRStatus } from "../../services/purchaseRequisitionService";
import PRStatsCards from "../../components/PurchaseRequisition/PRStatsCards";
import PRTable from "../../components/PurchaseRequisition/PRTable";
import CreatePurchaseRequisitionModal from "./CreatePurchaseRequisitionModal";
const PurchaseRequisitionPage = () => { const navigate = useNavigate(), [prs, setPrs] = useState([]), [open, setOpen] = useState(false); const load = useCallback(() => getAllPRs().then((res) => setPrs(res.data || [])).catch(() => toast.error("Could not load requisitions")), []); useEffect(() => { load(); }, [load]); const create = async (data) => { try { await createPR(data); toast.success("Purchase Requisition created"); setOpen(false); load(); } catch (error) { toast.error(error.response?.data?.message || "Could not create requisition"); } }; const status = async (id, value) => { try { await updatePRStatus(id, value); load(); } catch (error) { toast.error(error.response?.data?.message || "Status update failed"); } }; return <div className="p-6 space-y-6"><div className="flex justify-between"><div><h1 className="text-2xl font-bold">Purchase Requisitions</h1><p className="text-sm opacity-70">Canonical Product, Raw Material, and Component sourcing requests</p></div><button className="btn btn-primary" onClick={() => setOpen(true)}>New PR</button></div><PRStatsCards prs={prs}/><PRTable prs={prs} onStatus={status} onRFQ={(id) => navigate(`/procurement/rfq/create?purchaseRequisition=${id}`)}/><CreatePurchaseRequisitionModal open={open} onClose={() => setOpen(false)} onSubmit={create}/></div>; };
export default PurchaseRequisitionPage;
