import React, { useCallback, useEffect, useMemo, useState } from "react";
import toast from "react-hot-toast";
import { FiEdit2, FiPlus, FiSearch, FiTrash2, FiX } from "react-icons/fi";
import { listSettings } from "../services/productSettingsService.js";
import { createMasterRecord, deactivateMasterRecord, listMasterRecords, updateMasterRecord } from "../services/productMasterService.js";

const statusOptions = [{ value: "Active", label: "Active" }, { value: "Inactive", label: "Inactive" }];
const baseFields = [
  { name: "description", label: "Description", type: "textarea" },
  { name: "category", label: "Category", type: "select", source: "categories", required: true },
  { name: "unit", label: "Unit", type: "select", source: "units", required: true },
  { name: "hsnCode", label: "HSN code", type: "select", source: "hsn-codes" },
  { name: "costPrice", label: "Cost price", type: "number", min: 0, defaultValue: 0 },
  { name: "reorderLevel", label: "Reorder level", type: "number", min: 0, defaultValue: 0 },
  { name: "status", label: "Status", type: "select", options: statusOptions, defaultValue: "Active" },
];
const definitions = {
  products: {
    title: "Products", singular: "Product", code: "productCode", name: "productName",
    fields: [
      { name: "productCode", label: "Product code / SKU", required: true }, { name: "productName", label: "Product name", required: true },
      { name: "productType", label: "Product type", type: "select", required: true, defaultValue: "Finished Product", options: ["Raw Material", "Finished Product", "Service"].map((value) => ({ value, label: value })) },
      baseFields[0], baseFields[1], { name: "subCategory", label: "Subcategory", type: "select", source: "subcategories" },
      { name: "brand", label: "Brand", type: "select", source: "brands" }, baseFields[2], baseFields[3], baseFields[4],
      { name: "sellingPrice", label: "Selling price", type: "number", min: 0, defaultValue: 0 }, { name: "mrp", label: "MRP", type: "number", min: 0, defaultValue: 0 },
      { name: "discount", label: "Discount %", type: "number", min: 0, max: 100, defaultValue: 0 }, baseFields[5], baseFields[6],
    ],
  },
  "raw-materials": { title: "Raw Materials", singular: "Raw Material", code: "materialCode", name: "materialName", fields: [{ name: "materialCode", label: "Material code", required: true }, { name: "materialName", label: "Material name", required: true }, ...baseFields] },
  components: { title: "Components", singular: "Component", code: "componentCode", name: "componentName", fields: [{ name: "componentCode", label: "Component code", required: true }, { name: "componentName", label: "Component name", required: true }, ...baseFields] },
};
const empty = (fields) => Object.fromEntries(fields.map((field) => [field.name, field.defaultValue ?? ""]));
const refId = (value) => value?._id || value || "";

export default function ProductMasterPage({ resource }) {
  const definition = definitions[resource];
  const [records, setRecords] = useState([]), [options, setOptions] = useState({}), [search, setSearch] = useState(""), [query, setQuery] = useState(""), [statusFilter, setStatusFilter] = useState(""), [page, setPage] = useState(1), [totalPages, setTotalPages] = useState(1), [loading, setLoading] = useState(true), [modal, setModal] = useState(false), [editing, setEditing] = useState(null), [saving, setSaving] = useState(false), [form, setForm] = useState(() => empty(definition.fields));
  const load = useCallback(async () => { setLoading(true); try { const result = await listMasterRecords(resource, { page, limit: 10, search: query, status: statusFilter }); setRecords(result.data || []); setTotalPages(result.totalPages || 1); } catch (error) { toast.error(error.response?.data?.message || `Unable to load ${definition.title}`); } finally { setLoading(false); } }, [definition.title, page, query, resource, statusFilter]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const sources = [...new Set(definition.fields.map((field) => field.source).filter(Boolean))]; Promise.all(sources.map(async (source) => [source, (await listSettings(source, { limit: 200 })).data || []])).then((entries) => setOptions(Object.fromEntries(entries))).catch(() => toast.error("Unable to load Product Settings")); }, [definition.fields]);
  const subcategories = useMemo(() => (options.subcategories || []).filter((item) => refId(item.category) === form.category), [form.category, options.subcategories]);
  const openCreate = () => { setEditing(null); setForm(empty(definition.fields)); setModal(true); };
  const openEdit = (record) => { setEditing(record._id); setForm(Object.fromEntries(definition.fields.map((field) => [field.name, field.source ? refId(record[field.name]) : record[field.name] ?? field.defaultValue ?? ""]))); setModal(true); };
  const save = async (event) => { event.preventDefault(); setSaving(true); try { if (editing) await updateMasterRecord(resource, editing, form); else await createMasterRecord(resource, form); toast.success(`${definition.singular} ${editing ? "updated" : "created"}`); setModal(false); await load(); } catch (error) { toast.error(error.response?.data?.message || `Unable to save ${definition.singular.toLowerCase()}`); } finally { setSaving(false); } };
  const deactivate = async (record) => { if (!window.confirm(`Deactivate ${record[definition.name]}?`)) return; try { await deactivateMasterRecord(resource, record._id); toast.success(`${definition.singular} deactivated`); await load(); } catch (error) { toast.error(error.response?.data?.message || "Unable to deactivate record"); } };
  const optionLabel = (source, item) => source === "hsn-codes" ? `${item.hsnCode} (${item.gstPercentage}% GST)` : source === "subcategories" ? item.name : source === "warehouses" ? item.warehouseName : item.name;
  return <div className="mt-4 pb-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold text-gray-900">{definition.title}</h1><p className="mt-1 text-sm text-gray-500">Manage master definitions independently from inventory transactions.</p></div><button onClick={openCreate} className="inline-flex items-center justify-center gap-2 rounded-lg bg-orange-500 px-5 py-3 font-semibold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-orange-600 hover:shadow-md"><FiPlus/> Add {definition.singular}</button></div>
    <form onSubmit={(event) => { event.preventDefault(); setPage(1); setQuery(search.trim()); }} className="mt-5 flex flex-col gap-2 sm:flex-row"><label className="relative max-w-xl flex-1"><FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={`Search ${definition.title.toLowerCase()}`} className="w-full rounded-lg border py-2.5 pl-10 pr-3 outline-none focus:border-orange-500 focus:ring-4 focus:ring-orange-100"/></label><select value={statusFilter} onChange={(e) => { setPage(1); setStatusFilter(e.target.value); }} className="rounded-lg border bg-white px-3 py-2.5"><option value="">All statuses</option>{statusOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><button className="rounded-lg border bg-white px-5 py-2.5 font-medium hover:bg-gray-50">Search</button></form>
    <div className="mt-5 overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full min-w-[760px]"><thead className="bg-gray-50 text-sm text-gray-600"><tr>{["Code", "Name", "Category", "Unit", "Cost Price", "Status", "Actions"].map((heading) => <th key={heading} className={`p-4 font-semibold ${heading === "Actions" ? "text-right" : "text-left"}`}>{heading}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan="7" className="p-10 text-center text-gray-500">Loading...</td></tr> : records.length === 0 ? <tr><td colSpan="7" className="p-10 text-center text-gray-500">No records found.</td></tr> : records.map((record) => <tr key={record._id} className="border-t hover:bg-orange-50/30"><td className="p-4 font-medium">{record[definition.code]}</td><td className="p-4">{record[definition.name]}</td><td className="p-4">{record.category?.name}</td><td className="p-4">{record.unit?.name}</td><td className="p-4">₹{Number(record.costPrice || 0).toLocaleString("en-IN")}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${record.status === "Active" ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-600"}`}>{record.status}</span></td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={() => openEdit(record)} className="rounded p-2 text-amber-600 hover:bg-amber-50" title="Edit"><FiEdit2/></button><button disabled={record.status === "Inactive"} onClick={() => deactivate(record)} className="rounded p-2 text-red-600 hover:bg-red-50 disabled:opacity-30" title="Deactivate"><FiTrash2/></button></div></td></tr>)}</tbody></table><div className="flex justify-between border-t p-4 text-sm"><span>Page {page} of {totalPages}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">Previous</button><button disabled={page >= totalPages} onClick={() => setPage((value) => value + 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">Next</button></div></div></div>
    {modal && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/40 p-4"><form onSubmit={save} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b px-6 py-4"><h2 className="text-lg font-semibold">{editing ? "Edit" : "Add"} {definition.singular}</h2><button type="button" onClick={() => setModal(false)} className="rounded p-2 hover:bg-gray-100"><FiX/></button></div><div className="grid gap-4 p-6 sm:grid-cols-2">{definition.fields.map((field) => <label key={field.name} className={field.type === "textarea" ? "sm:col-span-2" : ""}><span className="mb-1.5 block text-sm font-medium">{field.label}{field.required && <span className="text-red-500"> *</span>}</span>{field.type === "textarea" ? <textarea rows="3" value={form[field.name]} onChange={(e) => setForm({ ...form, [field.name]: e.target.value })} className="w-full rounded-lg border px-3 py-2.5 focus:border-orange-500 focus:outline-none focus:ring-4 focus:ring-orange-100"/> : field.type === "select" ? <select required={field.required} value={form[field.name]} onChange={(e) => setForm({ ...form, [field.name]: e.target.value, ...(field.name === "category" ? { subCategory: "" } : {}) })} className="w-full rounded-lg border bg-white px-3 py-2.5"><option value="">Select {field.label.toLowerCase()}</option>{(field.options || (field.source === "subcategories" ? subcategories : options[field.source]) || []).map((item) => <option key={item.value || item._id} value={item.value || item._id}>{item.label || optionLabel(field.source, item)}</option>)}</select> : <input type={field.type || "text"} min={field.min} max={field.max} required={field.required} value={form[field.name]} onChange={(e) => setForm({ ...form, [field.name]: e.target.value })} className="w-full rounded-lg border px-3 py-2.5 focus:border-orange-500 focus:outline-none focus:ring-4 focus:ring-orange-100"/>}</label>)}</div><div className="flex justify-end gap-3 border-t px-6 py-4"><button type="button" onClick={() => setModal(false)} className="rounded-lg border px-4 py-2">Cancel</button><button disabled={saving} className="rounded-lg bg-orange-500 px-5 py-2 font-semibold text-white hover:bg-orange-600 disabled:opacity-60">{saving ? "Saving..." : "Save"}</button></div></form></div>}
  </div>;
}
