import React, { useEffect, useMemo, useState } from "react";
import toast from "react-hot-toast";
import { listSettings } from "../../services/productSettingsService.js";
import { listMasterRecords } from "../../services/productMasterService.js";
import { auditStock, getAudits, getInventory, getReorderAlerts, getTransactions, stockIn, stockOut, transferStock } from "../../services/inventoryService.js";

const types = [{ value: "Product", label: "Product", resource: "products" }, { value: "RawMaterial", label: "Raw Material", resource: "raw-materials" }, { value: "Component", label: "Component", resource: "components" }];
const names = (item) => ({ code: item?.productCode || item?.materialCode || item?.componentCode || "—", name: item?.productName || item?.materialName || item?.componentName || "—" });
const initial = { itemType: "Product", item: "", warehouse: "", sourceWarehouse: "", destinationWarehouse: "", quantity: "", physicalQuantity: "", reason: "", referenceType: "Manual", referenceId: "", notes: "" };

export default function InventoryWorkspace({ mode = "overview" }) {
  const [rows, setRows] = useState([]), [items, setItems] = useState([]), [warehouses, setWarehouses] = useState([]), [form, setForm] = useState(initial), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [filters, setFilters] = useState({ search: "", itemType: "", warehouse: "", stockStatus: "" });
  const title = ({ overview: "Stock Overview", in: "Stock In", out: "Stock Out", transfer: "Stock Transfer", audit: "Stock Audit", transactions: "Transactions", reorder: "Reorder Alerts" })[mode];
  useEffect(() => { listSettings("warehouses", { limit: 200 }).then((result) => setWarehouses(result.data || [])).catch(() => toast.error("Unable to load warehouses")); }, []);
  useEffect(() => { const selected = types.find((type) => type.value === form.itemType); listMasterRecords(selected.resource, { limit: 200, status: "Active" }).then((result) => { setItems(result.data || []); setForm((old) => ({ ...old, item: "" })); }).catch(() => toast.error("Unable to load items")); }, [form.itemType]);
  const load = async () => { setLoading(true); try { const result = mode === "transactions" ? await getTransactions(filters) : mode === "audit" ? await getAudits(filters) : mode === "reorder" ? await getReorderAlerts(filters) : await getInventory(filters); setRows(result.data || []); } catch (error) { toast.error(error.response?.data?.message || "Unable to load inventory"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [mode]);
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { if (mode === "in") await stockIn(form); if (mode === "out") await stockOut(form); if (mode === "transfer") await transferStock(form); if (mode === "audit") await auditStock(form); toast.success(`${title} completed`); setForm((old) => ({ ...initial, itemType: old.itemType })); await load(); } catch (error) { toast.error(error.response?.data?.message || `${title} failed`); } finally { setSaving(false); } };
  const selectedItems = useMemo(() => items.map((item) => ({ ...item, display: `${names(item).code} — ${names(item).name}` })), [items]);
  const fieldClass = "w-full rounded-lg border border-gray-300 bg-white px-3 py-2.5 outline-none focus:border-orange-500 focus:ring-4 focus:ring-orange-100";
  const formMode = ["in", "out", "transfer", "audit"].includes(mode);
  return <div className="mt-4 pb-8"><h1 className="text-2xl font-bold text-gray-900">{title}</h1><p className="mt-1 text-sm text-gray-500">Warehouse-level inventory with an auditable movement ledger.</p>
    {formMode && <form onSubmit={submit} className="mt-5 grid gap-4 rounded-xl border bg-white p-5 shadow-sm md:grid-cols-2"><label><span className="mb-1 block text-sm font-medium">Item type</span><select className={fieldClass} value={form.itemType} onChange={(e) => setForm({ ...form, itemType: e.target.value })}>{types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select></label><label><span className="mb-1 block text-sm font-medium">Item</span><select required className={fieldClass} value={form.item} onChange={(e) => setForm({ ...form, item: e.target.value })}><option value="">Select item</option>{selectedItems.map((item) => <option key={item._id} value={item._id}>{item.display}</option>)}</select></label>
      {mode === "transfer" ? <><label><span className="mb-1 block text-sm font-medium">Source warehouse</span><select required className={fieldClass} value={form.sourceWarehouse} onChange={(e) => setForm({ ...form, sourceWarehouse: e.target.value })}><option value="">Select source</option>{warehouses.map((w) => <option key={w._id} value={w._id}>{w.warehouseName}</option>)}</select></label><label><span className="mb-1 block text-sm font-medium">Destination warehouse</span><select required className={fieldClass} value={form.destinationWarehouse} onChange={(e) => setForm({ ...form, destinationWarehouse: e.target.value })}><option value="">Select destination</option>{warehouses.map((w) => <option key={w._id} value={w._id}>{w.warehouseName}</option>)}</select></label></> : <label><span className="mb-1 block text-sm font-medium">Warehouse</span><select required className={fieldClass} value={form.warehouse} onChange={(e) => setForm({ ...form, warehouse: e.target.value })}><option value="">Select warehouse</option>{warehouses.map((w) => <option key={w._id} value={w._id}>{w.warehouseName}</option>)}</select></label>}
      <label><span className="mb-1 block text-sm font-medium">{mode === "audit" ? "Physical quantity" : "Quantity"}</span><input required min="0" step="any" type="number" className={fieldClass} value={mode === "audit" ? form.physicalQuantity : form.quantity} onChange={(e) => setForm({ ...form, [mode === "audit" ? "physicalQuantity" : "quantity"]: e.target.value })}/></label><label><span className="mb-1 block text-sm font-medium">Reason</span><input className={fieldClass} value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })}/></label><label className="md:col-span-2"><span className="mb-1 block text-sm font-medium">Notes</span><textarea className={fieldClass} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })}/></label><button disabled={saving} className="rounded-lg bg-orange-500 px-5 py-3 font-semibold text-white transition hover:bg-orange-600 disabled:opacity-50 md:w-64">{saving ? "Processing..." : title}</button></form>}
    {!formMode && <div className="mt-5 grid gap-3 md:grid-cols-5"><input className={fieldClass} placeholder="Search" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })}/><select className={fieldClass} value={filters.itemType} onChange={(e) => setFilters({ ...filters, itemType: e.target.value })}><option value="">All item types</option>{types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select><select className={fieldClass} value={filters.warehouse} onChange={(e) => setFilters({ ...filters, warehouse: e.target.value })}><option value="">All warehouses</option>{warehouses.map((w) => <option key={w._id} value={w._id}>{w.warehouseName}</option>)}</select><select className={fieldClass} value={filters.stockStatus} onChange={(e) => setFilters({ ...filters, stockStatus: e.target.value })}><option value="">All stock statuses</option><option>In Stock</option><option>Low Stock</option><option>Out of Stock</option></select><button onClick={load} className="rounded-lg border bg-white px-4 font-medium hover:bg-gray-50">Apply filters</button></div>}
    <div className="mt-5 overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full min-w-[800px]"><thead className="bg-gray-50"><tr>{["Item Type", "Code", "Item", "Warehouse", mode === "audit" ? "Difference" : "Quantity", "Status / Movement", "Date"].map((h) => <th key={h} className="p-4 text-left text-sm font-semibold text-gray-600">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan="7" className="p-10 text-center">Loading...</td></tr> : rows.length === 0 ? <tr><td colSpan="7" className="p-10 text-center text-gray-500">No records found.</td></tr> : rows.map((row, index) => { const item = row.item || {}; const identity = names(item); return <tr key={row._id || `${row.itemType}-${item._id}-${index}`} className="border-t"><td className="p-4">{row.itemType}</td><td className="p-4 font-medium">{identity.code}</td><td className="p-4">{identity.name}</td><td className="p-4">{row.warehouse?.warehouseName || (mode === "reorder" ? "All warehouses" : "—")}</td><td className="p-4">{mode === "audit" ? row.difference : row.quantity}</td><td className="p-4">{row.stockStatus || row.movementType || "—"}</td><td className="p-4">{row.createdAt ? new Date(row.createdAt).toLocaleString() : "—"}</td></tr>; })}</tbody></table></div>
  </div>;
}
