import { useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { getAllPurchaseOrders } from "../../services/purchaseOrderService";
import { createPurchaseBill, previewPurchaseBill, submitPurchaseBill } from "../../services/purchaseBillService";

const CreatePurchaseBill = () => {
  const navigate = useNavigate(), [params] = useSearchParams(), [orders, setOrders] = useState([]), [poId, setPoId] = useState(params.get("purchaseOrder") || ""), [header, setHeader] = useState({ supplierInvoiceNumber: "", invoiceDate: new Date().toISOString().slice(0, 10), dueDate: "", notes: "" }), [lines, setLines] = useState([]), [preview, setPreview] = useState(null), [busy, setBusy] = useState(false);
  useEffect(() => { getAllPurchaseOrders().then((data) => setOrders(data.filter((po) => ["APPROVED","SENT","PARTIALLY_RECEIVED","RECEIVED"].includes(po.status)))).catch(() => toast.error("Could not load Purchase Orders")); }, []);
  const po = useMemo(() => orders.find((entry) => entry._id === poId), [orders, poId]);
  useEffect(() => { if (!po) { setLines([]); setPreview(null); return; } const seeds = po.items.map((line) => ({ poLineId: line._id, quantity: 1, unitPrice: Number(line.unitPrice || 0), discount: 0, tax: 0 })); setLines(seeds); previewPurchaseBill({ purchaseOrder: po._id, supplier: po.vendorId?._id || po.vendorId, supplierInvoiceNumber: "PREVIEW", invoiceDate: new Date().toISOString().slice(0, 10), currency: "INR", lines: seeds }).then((result) => { setPreview(result); setLines(seeds.map((line) => { const context = result.lines.find((candidate) => candidate.poLineId === line.poLineId)?.matchResult; return { ...line, quantity: Math.max(0, Number(context?.remainingBillableQuantity || 0)) }; })); }).catch(() => setPreview(null)); }, [po]);
  const payload = () => ({ ...header, purchaseOrder: po._id, supplier: po.vendorId?._id || po.vendorId, currency: "INR", lines: lines.filter((line) => Number(line.quantity) > 0) });
  const updateLine = (index, key, value) => { setLines((current) => current.map((line, i) => i === index ? { ...line, [key]: value } : line)); setPreview(null); };
  const runPreview = async () => { if (!po) return toast.error("Select a Purchase Order"); try { setPreview(await previewPurchaseBill(payload())); } catch (error) { toast.error(error.response?.data?.message || "Preview failed"); } };
  const save = async (submitNow) => { if (!po) return toast.error("Select a Purchase Order"); setBusy(true); try { let bill = await createPurchaseBill(payload()); if (submitNow) bill = await submitPurchaseBill(bill._id); toast.success(submitNow ? "Bill created and matched" : "Draft saved"); navigate(`/procurement/purchase-bills/${bill._id}`); } catch (error) { toast.error(error.response?.data?.message || "Could not create Purchase Bill"); } finally { setBusy(false); } };
  return <div className="p-6"><div className="bg-base-100 rounded-xl shadow p-6 space-y-6"><div><h1 className="text-2xl font-bold">New Purchase Bill</h1><p className="text-sm opacity-70">Canonical items come from the PO. Receipt quantities come only from Posted GRNs.</p></div><div className="grid md:grid-cols-2 gap-4"><label className="form-control"><span className="label-text mb-1">Purchase Order</span><select className="select select-bordered" value={poId} onChange={(e) => setPoId(e.target.value)} required><option value="">Select approved PO</option>{orders.map((entry) => <option key={entry._id} value={entry._id}>{entry.poNumber} — {entry.vendorId?.vendorName}</option>)}</select></label><label className="form-control"><span className="label-text mb-1">Supplier</span><input className="input input-bordered" readOnly value={po?.vendorId?.vendorName || "Selected from PO"}/></label><label className="form-control"><span className="label-text mb-1">Supplier invoice number</span><input className="input input-bordered" value={header.supplierInvoiceNumber} onChange={(e) => setHeader({ ...header, supplierInvoiceNumber: e.target.value })} required/></label><label className="form-control"><span className="label-text mb-1">Invoice date</span><input type="date" className="input input-bordered" value={header.invoiceDate} onChange={(e) => setHeader({ ...header, invoiceDate: e.target.value })}/></label><label className="form-control"><span className="label-text mb-1">Due date</span><input type="date" className="input input-bordered" value={header.dueDate} onChange={(e) => setHeader({ ...header, dueDate: e.target.value })}/></label></div>
    {po && <div className="overflow-x-auto"><table className="table"><thead><tr><th>Item</th><th>Type</th><th>Ordered</th><th>Accepted receipt</th><th>Previously billed</th><th>PO price</th><th>Bill qty</th><th>Bill price</th><th>Discount</th><th>Tax</th><th>Preview</th></tr></thead><tbody>{po.items.map((poLine, index) => { const match = preview?.lines?.find((candidate) => candidate.poLineId === poLine._id)?.matchResult; return <tr key={poLine._id}><td>{poLine.itemNameSnapshot || poLine.item?.productName || poLine.item?.materialName || poLine.item?.componentName}</td><td>{poLine.itemType}</td><td>{poLine.quantity}</td><td>{match?.receivedQuantity ?? "Previewing…"}</td><td>{match?.previouslyBilledQuantity ?? "—"}</td><td>₹{Number(poLine.unitPrice).toFixed(2)}</td><td><input type="number" min="0" step="0.000001" className="input input-bordered input-sm w-28" value={lines[index]?.quantity ?? ""} onChange={(e) => updateLine(index, "quantity", e.target.value)}/></td><td><input type="number" min="0" step="0.01" className="input input-bordered input-sm w-28" value={lines[index]?.unitPrice ?? ""} onChange={(e) => updateLine(index, "unitPrice", e.target.value)}/></td><td><input type="number" min="0" step="0.01" className="input input-bordered input-sm w-24" value={lines[index]?.discount ?? 0} onChange={(e) => updateLine(index, "discount", e.target.value)}/></td><td><input type="number" min="0" step="0.01" className="input input-bordered input-sm w-24" value={lines[index]?.tax ?? 0} onChange={(e) => updateLine(index, "tax", e.target.value)}/></td><td>{match ? <div><span className={`badge ${match.status === "MATCHED" ? "badge-success" : "badge-error"}`}>{match.status}</span><div className="text-xs mt-1">Available {match.remainingBillableQuantity}</div>{match.reasons?.map((r) => <div className="text-xs text-error" key={r.code}>{r.message}</div>)}</div> : "—"}</td></tr>; })}</tbody></table></div>}
    <textarea className="textarea textarea-bordered w-full" placeholder="Notes" value={header.notes} onChange={(e) => setHeader({ ...header, notes: e.target.value })}/><div className="flex flex-wrap gap-2"><button type="button" className="btn btn-outline" onClick={runPreview} disabled={!po || busy}>Preview match</button><button type="button" className="btn" onClick={() => save(false)} disabled={!po || busy}>Save Draft</button><button type="button" className="btn btn-primary" onClick={() => save(true)} disabled={!po || busy}>Create & Submit</button></div></div></div>;
};
export default CreatePurchaseBill;
