import { useCallback, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import toast from "react-hot-toast";
import { approvePurchaseBill, approvePurchaseBillException, getPurchaseBill, rejectPurchaseBill, rematchPurchaseBill, submitPurchaseBill } from "../../services/purchaseBillService";
const money = (minor) => `₹${(Number(minor || 0) / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
const PurchaseBillDetails = () => {
  const { id } = useParams(); const [bill, setBill] = useState(null), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setBill(await getPurchaseBill(id)); } catch (error) { toast.error(error.response?.data?.message || "Could not load Purchase Bill"); } }, [id]); useEffect(() => { load(); }, [load]);
  const run = async (operation, message, needsReason = false) => { const reason = needsReason ? window.prompt(message) : ""; if (needsReason && !reason) return; setBusy(true); try { await operation(id, reason); toast.success(message); await load(); } catch (error) { toast.error(error.response?.data?.message || "Action failed"); } finally { setBusy(false); } };
  if (!bill) return <div className="p-6">Loading…</div>;
  return <div className="p-6 space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold">{bill.billNumber}</h1><p>{bill.supplier?.vendorName} · Invoice {bill.supplierInvoiceNumber} · PO {bill.purchaseOrder?.poNumber}</p><p className="text-sm opacity-70">GRNs considered: {bill.grnsConsidered?.map((g) => g.grnNumber).join(", ") || "None"}</p></div><div className="flex flex-wrap gap-2 items-center"><span className="badge badge-lg">{bill.status}</span><span className={`badge badge-lg ${bill.matchStatus === "MATCHED" ? "badge-success" : bill.matchStatus === "EXCEPTION" ? "badge-error" : ""}`}>{bill.matchStatus}</span>{bill.status === "DRAFT" && <button className="btn btn-primary btn-sm" disabled={busy} onClick={() => run(submitPurchaseBill, "Bill submitted")}>Submit</button>}{bill.status === "SUBMITTED" && <button className="btn btn-sm" disabled={busy} onClick={() => run(rematchPurchaseBill, "Bill rematched")}>Rematch</button>}{bill.status === "SUBMITTED" && bill.matchStatus === "MATCHED" && <button className="btn btn-success btn-sm" disabled={busy} onClick={() => run(approvePurchaseBill, "Bill approved")}>Approve</button>}{bill.status === "SUBMITTED" && bill.matchStatus === "EXCEPTION" && <button className="btn btn-warning btn-sm" disabled={busy} onClick={() => run(approvePurchaseBillException, "Enter required exception override justification", true)}>Approve Exception</button>}{bill.status === "SUBMITTED" && <button className="btn btn-error btn-outline btn-sm" disabled={busy} onClick={() => run(rejectPurchaseBill, "Enter rejection reason", true)}>Reject</button>}</div></div>
    <div className="grid md:grid-cols-4 gap-3">{[["Invoice date",new Date(bill.invoiceDate).toLocaleDateString()],["Due date",bill.dueDate ? new Date(bill.dueDate).toLocaleDateString() : "—"],["Currency",bill.currency],["Grand total",money(bill.grandTotalMinor)]].map(([label,value]) => <div className="stat bg-base-100 rounded-xl shadow" key={label}><div className="stat-title">{label}</div><div className="stat-value text-xl">{value}</div></div>)}</div>
    <div className="overflow-x-auto bg-base-100 rounded-xl shadow"><table className="table"><thead><tr><th>Item</th><th>PO</th><th>GRN accepted</th><th>Previously billed</th><th>This bill</th><th>Prices</th><th>Result</th></tr></thead><tbody>{bill.lines.map((line) => <tr key={line._id}><td><div className="font-medium">{line.itemNameSnapshot}</div><div className="text-xs opacity-60">{line.itemCodeSnapshot} · {line.itemType}</div></td><td>Ordered {line.matchResult?.orderedQuantity ?? "—"}</td><td>{line.matchResult?.receivedQuantity ?? "—"}</td><td>{line.matchResult?.previouslyBilledQuantity ?? "—"}</td><td>{line.quantity}</td><td><div>PO {money(line.matchResult?.poUnitPriceMinor)}</div><div>Bill {money(line.unitPriceMinor)}</div></td><td><span className={`badge ${line.matchResult?.status === "MATCHED" ? "badge-success" : "badge-error"}`}>{line.matchResult?.status || "NOT CHECKED"}</span>{line.matchResult?.reasons?.map((reason) => <div className="text-xs text-error mt-1" key={`${reason.code}-${reason.message}`}>{reason.message}</div>)}</td></tr>)}</tbody></table></div>
    <div className="grid md:grid-cols-2 gap-4"><div className="bg-base-100 rounded-xl shadow p-5"><h2 className="font-bold text-lg mb-3">Totals</h2><p>Subtotal: {money(bill.subtotalMinor)}</p><p>Discount: {money(bill.discountTotalMinor)}</p><p>Tax: {money(bill.taxTotalMinor)}</p><p className="font-bold">Grand total: {money(bill.grandTotalMinor)}</p></div><div className="bg-base-100 rounded-xl shadow p-5"><h2 className="font-bold text-lg mb-3">Audit trail</h2><div className="space-y-2">{bill.auditTrail.map((entry) => <div key={entry._id} className="text-sm"><span className="font-semibold">{entry.action}</span> · {entry.user?.name || "User"} · {new Date(entry.at).toLocaleString()}{entry.reason && <div className="opacity-70">{entry.reason}</div>}</div>)}</div></div></div>
    {bill.exceptionOverride?.approved && <div className="alert alert-warning"><span>Exception override: {bill.exceptionOverride.reason} — {bill.exceptionOverride.approvedBy?.name}</span></div>}
  </div>;
};
export default PurchaseBillDetails;
