import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import { getPurchaseBills } from "../../services/purchaseBillService";

const money = (minor) => `₹${(Number(minor || 0) / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
const PurchaseBillList = () => {
  const [result, setResult] = useState({ data: [], pagination: { page: 1, pages: 1 } }); const [filters, setFilters] = useState({ search: "", status: "", matchStatus: "", page: 1, limit: 10 }); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setResult(await getPurchaseBills(filters)); } catch (error) { toast.error(error.response?.data?.message || "Could not load Purchase Bills"); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { load(); }, [load]);
  const change = (key, value) => setFilters((current) => ({ ...current, [key]: value, page: key === "page" ? value : 1 }));
  return <div className="p-6 space-y-5"><div className="flex flex-wrap justify-between gap-3 items-center"><div><h1 className="text-2xl font-bold">Purchase Bills</h1><p className="text-sm opacity-70">Supplier invoices matched against Purchase Orders and posted receipts.</p></div><Link className="btn btn-primary" to="/procurement/purchase-bills/new">New Purchase Bill</Link></div>
    <div className="grid md:grid-cols-3 gap-3 bg-base-100 rounded-xl shadow p-4"><input className="input input-bordered" placeholder="Search bill or supplier invoice" value={filters.search} onChange={(e) => change("search", e.target.value)}/><select className="select select-bordered" value={filters.status} onChange={(e) => change("status", e.target.value)}><option value="">All lifecycle statuses</option>{["DRAFT","SUBMITTED","APPROVED","REJECTED","CANCELLED"].map((v) => <option key={v}>{v}</option>)}</select><select className="select select-bordered" value={filters.matchStatus} onChange={(e) => change("matchStatus", e.target.value)}><option value="">All match statuses</option>{["NOT_CHECKED","MATCHED","EXCEPTION"].map((v) => <option key={v}>{v}</option>)}</select></div>
    <div className="overflow-x-auto bg-base-100 rounded-xl shadow"><table className="table table-zebra"><thead><tr><th>Bill</th><th>Supplier invoice</th><th>Supplier</th><th>PO</th><th>Invoice date</th><th>Due</th><th>Total</th><th>Status</th><th>Match</th></tr></thead><tbody>{loading ? <tr><td colSpan="9">Loading…</td></tr> : result.data.length ? result.data.map((bill) => <tr key={bill._id}><td><Link className="link link-primary font-medium" to={`/procurement/purchase-bills/${bill._id}`}>{bill.billNumber}</Link></td><td>{bill.supplierInvoiceNumber}</td><td>{bill.supplier?.vendorName}</td><td>{bill.purchaseOrder?.poNumber}</td><td>{new Date(bill.invoiceDate).toLocaleDateString()}</td><td>{bill.dueDate ? new Date(bill.dueDate).toLocaleDateString() : "—"}</td><td>{money(bill.grandTotalMinor)}</td><td><span className="badge">{bill.status}</span></td><td><span className={`badge ${bill.matchStatus === "MATCHED" ? "badge-success" : bill.matchStatus === "EXCEPTION" ? "badge-error" : ""}`}>{bill.matchStatus}</span></td></tr>) : <tr><td colSpan="9" className="text-center opacity-60">No Purchase Bills found.</td></tr>}</tbody></table></div>
    <div className="flex justify-end gap-2 items-center"><button className="btn btn-sm" disabled={result.pagination.page <= 1} onClick={() => change("page", result.pagination.page - 1)}>Previous</button><span>Page {result.pagination.page} of {Math.max(1, result.pagination.pages)}</span><button className="btn btn-sm" disabled={result.pagination.page >= result.pagination.pages} onClick={() => change("page", result.pagination.page + 1)}>Next</button></div>
  </div>;
};
export default PurchaseBillList;
