import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import { getAccountsPayable, getAccountsPayableAging, getAccountsPayableSummary } from "../../services/accountsPayableService";
const money = (minor) => `₹${(Number(minor || 0) / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
const AccountsPayable = () => {
  const [result, setResult] = useState({ data: [], pagination: { page: 1, pages: 1 } }), [summary, setSummary] = useState({}), [aging, setAging] = useState({ buckets: {} }), [filters, setFilters] = useState({ search: "", supplier: "", status: "", overdue: "", dueFrom: "", dueTo: "", page: 1, limit: 10 });
  const load = useCallback(async () => { try { const [rows, totals, buckets] = await Promise.all([getAccountsPayable(filters), getAccountsPayableSummary(), getAccountsPayableAging()]); setResult(rows); setSummary(totals); setAging(buckets); } catch (error) { toast.error(error.response?.data?.message || "Could not load Accounts Payable"); } }, [filters]); useEffect(() => { load(); }, [load]);
  const change = (key, value) => setFilters((current) => ({ ...current, [key]: value, page: key === "page" ? value : 1 }));
  const cards = [["Outstanding",summary.totalOutstandingMinor],["Overdue",summary.overdueTotalMinor],["Due within 7 days",summary.dueWithin7DaysMinor],["Due within 30 days",summary.dueWithin30DaysMinor]];
  const supplierOptions = summary.supplierTotals || [];
  return <div className="p-6 space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Accounts Payable</h1><p className="text-sm opacity-70">Approved supplier bills and their settlement balances.</p></div><Link className="btn btn-primary" to="/supplier-payments">Record Supplier Payment</Link></div><div className="grid md:grid-cols-4 gap-3">{cards.map(([label,value]) => <div className="stat bg-base-100 rounded-xl shadow" key={label}><div className="stat-title">{label}</div><div className="stat-value text-xl">{money(value)}</div></div>)}</div><div className="grid grid-cols-2 md:grid-cols-5 gap-2">{[["Current","CURRENT"],["1–30 days","1_30"],["31–60 days","31_60"],["61–90 days","61_90"],["90+ days","90_PLUS"]].map(([label,key]) => <div className="rounded-lg border bg-base-100 p-3" key={key}><div className="text-xs opacity-60">{label}</div><div className="font-semibold">{money(aging.buckets?.[key])}</div></div>)}</div>
    <div className="grid md:grid-cols-3 gap-3 bg-base-100 shadow rounded-xl p-4"><input className="input input-bordered" placeholder="Search bill or supplier invoice" value={filters.search} onChange={(e) => change("search", e.target.value)}/><select className="select select-bordered" value={filters.supplier} onChange={(e) => change("supplier", e.target.value)}><option value="">All suppliers</option>{supplierOptions.map((row) => <option key={row.supplier?._id} value={row.supplier?._id}>{row.supplier?.vendorName}</option>)}</select><select className="select select-bordered" value={filters.status} onChange={(e) => change("status", e.target.value)}><option value="">All statuses</option>{["OPEN","PARTIALLY_PAID","PAID","CANCELLED"].map((v) => <option key={v}>{v}</option>)}</select><select className="select select-bordered" value={filters.overdue} onChange={(e) => change("overdue", e.target.value)}><option value="">All due states</option><option value="true">Overdue only</option></select><input type="date" className="input input-bordered" value={filters.dueFrom} onChange={(e) => change("dueFrom", e.target.value)}/><input type="date" className="input input-bordered" value={filters.dueTo} onChange={(e) => change("dueTo", e.target.value)}/></div>
    <div className="overflow-x-auto bg-base-100 shadow rounded-xl"><table className="table table-zebra"><thead><tr><th>Supplier</th><th>Bill</th><th>Supplier invoice</th><th>Due</th><th>Original</th><th>Paid</th><th>Outstanding</th><th>Status</th><th>Overdue</th></tr></thead><tbody>{result.data.map((ap) => <tr key={ap._id}><td>{ap.supplier?.vendorName}</td><td><Link className="link link-primary" to={`/accounts-payable/${ap._id}`}>{ap.purchaseBill?.billNumber}</Link></td><td>{ap.purchaseBill?.supplierInvoiceNumber}</td><td>{ap.dueDate ? new Date(ap.dueDate).toLocaleDateString() : "—"}</td><td>{money(ap.originalAmountMinor)}</td><td>{money(ap.paidAmountMinor)}</td><td>{money(ap.outstandingAmountMinor)}</td><td><span className="badge">{ap.status}</span></td><td>{ap.overdue ? `${ap.daysOverdue} days` : "Current"}</td></tr>)}{!result.data.length && <tr><td colSpan="9" className="text-center opacity-60">No payable obligations found.</td></tr>}</tbody></table></div><div className="flex justify-end gap-2"><button className="btn btn-sm" disabled={result.pagination.page <= 1} onClick={() => change("page", result.pagination.page - 1)}>Previous</button><span>Page {result.pagination.page} of {Math.max(1,result.pagination.pages)}</span><button className="btn btn-sm" disabled={result.pagination.page >= result.pagination.pages} onClick={() => change("page", result.pagination.page + 1)}>Next</button></div>
  </div>;
};
export default AccountsPayable;
