import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { getAccountsPayable } from "../../services/accountsPayableService";
import { getSupplierPayments, previewSupplierPayment, recordSupplierPayment } from "../../services/supplierPaymentService";
const money = (minor) => `₹${(Number(minor || 0) / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
const freshKey = () => globalThis.crypto?.randomUUID?.() || `supplier-payment-${Date.now()}-${Math.random()}`;
const SupplierPayments = () => {
  const [params] = useSearchParams(), preselected = params.get("accountsPayable") || ""; const [payments,setPayments]=useState({data:[],pagination:{page:1,pages:1}}),[payables,setPayables]=useState([]),[filters,setFilters]=useState({search:"",status:"",paymentMethod:"",page:1,limit:10}),[supplier,setSupplier]=useState(""),[allocations,setAllocations]=useState({}),[form,setForm]=useState({paymentDate:new Date().toISOString().slice(0,10),paymentMethod:"BANK_TRANSFER",referenceNumber:"",notes:"",idempotencyKey:freshKey()}),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const [paymentRows,apRows]=await Promise.all([getSupplierPayments(filters),getAccountsPayable({limit:100})]);setPayments(paymentRows);setPayables(apRows.data.filter((ap)=>ap.outstandingAmountMinor>0));}catch(error){toast.error(error.response?.data?.message||"Could not load supplier finance data");}},[filters]); useEffect(()=>{load();},[load]);
  useEffect(()=>{if(!preselected||!payables.length)return;const ap=payables.find((row)=>row._id===preselected);if(ap){setSupplier(ap.supplier?._id||ap.supplier);setAllocations({[ap._id]:(ap.outstandingAmountMinor/100).toFixed(2)});}},[preselected,payables]);
  const supplierRows=useMemo(()=>payables.filter((ap)=>String(ap.supplier?._id||ap.supplier)===supplier),[payables,supplier]); const suppliers=useMemo(()=>[...new Map(payables.map((ap)=>[String(ap.supplier?._id||ap.supplier),ap.supplier])).entries()],[payables]);
  const proposed=()=>supplierRows.filter((ap)=>Number(allocations[ap._id])>0).map((ap)=>({accountsPayable:ap._id,amount:Number(allocations[ap._id])})); const total=proposed().reduce((sum,row)=>sum+row.amount,0); const payload=()=>({...form,supplier,totalAmount:total,currency:"INR",allocations:proposed()});
  const runPreview=async()=>{try{setPreview(await previewSupplierPayment(payload()));}catch(error){toast.error(error.response?.data?.message||"Payment preview failed");}}; const submit=async()=>{setBusy(true);try{const result=await recordSupplierPayment(payload());toast.success(result.message);setForm({paymentDate:new Date().toISOString().slice(0,10),paymentMethod:"BANK_TRANSFER",referenceNumber:"",notes:"",idempotencyKey:freshKey()});setAllocations({});setPreview(null);await load();}catch(error){toast.error(error.response?.data?.message||"Payment could not be recorded");}finally{setBusy(false);}};
  const changeFilter=(key,value)=>setFilters((current)=>({...current,[key]:value,page:key==="page"?value:1}));
  return <div className="p-6 space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Supplier Payments</h1><p className="text-sm opacity-70">Record externally completed payments against approved payable obligations.</p></div><Link className="btn btn-outline" to="/accounts-payable">Accounts Payable</Link></div>
    <div className="bg-base-100 rounded-xl shadow p-5 space-y-4"><h2 className="font-bold text-lg">Record Payment</h2><div className="grid md:grid-cols-4 gap-3"><select className="select select-bordered" value={supplier} onChange={(e)=>{setSupplier(e.target.value);setAllocations({});setPreview(null);}}><option value="">Select supplier</option>{suppliers.map(([id,value])=><option key={id} value={id}>{value?.vendorName}</option>)}</select><input type="date" className="input input-bordered" value={form.paymentDate} onChange={(e)=>setForm({...form,paymentDate:e.target.value})}/><select className="select select-bordered" value={form.paymentMethod} onChange={(e)=>setForm({...form,paymentMethod:e.target.value})}>{["BANK_TRANSFER","CHEQUE","CASH","UPI","OTHER"].map((v)=><option key={v}>{v}</option>)}</select><input className="input input-bordered" placeholder="External reference" value={form.referenceNumber} onChange={(e)=>setForm({...form,referenceNumber:e.target.value})}/></div>{supplier&&<div className="overflow-x-auto"><table className="table"><thead><tr><th>Bill</th><th>Supplier invoice</th><th>Due</th><th>Outstanding</th><th>Allocation</th><th>After payment</th></tr></thead><tbody>{supplierRows.map((ap)=>{const line=preview?.allocations?.find((row)=>row.accountsPayable?._id===ap._id);return <tr key={ap._id}><td>{ap.purchaseBill?.billNumber}</td><td>{ap.purchaseBill?.supplierInvoiceNumber}</td><td>{ap.dueDate?new Date(ap.dueDate).toLocaleDateString():"—"}</td><td>{money(ap.outstandingAmountMinor)}</td><td><input type="number" min="0" max={ap.outstandingAmountMinor/100} step="0.01" className="input input-bordered input-sm w-36" value={allocations[ap._id]||""} onChange={(e)=>{setAllocations({...allocations,[ap._id]:e.target.value});setPreview(null);}}/></td><td>{line?money(line.postPaymentOutstandingMinor):"—"}</td></tr>})}</tbody></table></div>}<textarea className="textarea textarea-bordered w-full" placeholder="Notes" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/><div className="flex flex-wrap justify-between items-center gap-3"><div className="font-bold">Payment total: ₹{total.toLocaleString("en-IN",{minimumFractionDigits:2})}</div><div className="flex gap-2"><button className="btn btn-outline" disabled={!supplier||!total||busy} onClick={runPreview}>Preview</button><button className="btn btn-primary" disabled={!preview||busy} onClick={submit}>{busy?"Recording…":"Record Payment"}</button></div></div></div>
    <div className="grid md:grid-cols-3 gap-3"><input className="input input-bordered" placeholder="Search payment or reference" value={filters.search} onChange={(e)=>changeFilter("search",e.target.value)}/><select className="select select-bordered" value={filters.status} onChange={(e)=>changeFilter("status",e.target.value)}><option value="">All statuses</option><option>RECORDED</option><option>REVERSED</option></select><select className="select select-bordered" value={filters.paymentMethod} onChange={(e)=>changeFilter("paymentMethod",e.target.value)}><option value="">All methods</option>{["BANK_TRANSFER","CHEQUE","CASH","UPI","OTHER"].map((v)=><option key={v}>{v}</option>)}</select></div><div className="overflow-x-auto bg-base-100 rounded-xl shadow"><table className="table table-zebra"><thead><tr><th>Payment</th><th>Supplier</th><th>Date</th><th>Method</th><th>Reference</th><th>Total</th><th>Status</th></tr></thead><tbody>{payments.data.map((payment)=><tr key={payment._id}><td><Link className="link link-primary" to={`/supplier-payments/${payment._id}`}>{payment.paymentNumber}</Link></td><td>{payment.supplier?.vendorName}</td><td>{new Date(payment.paymentDate).toLocaleDateString()}</td><td>{payment.paymentMethod}</td><td>{payment.referenceNumber||"—"}</td><td>{money(payment.totalAmountMinor)}</td><td><span className={`badge ${payment.status==="REVERSED"?"badge-error":"badge-success"}`}>{payment.status}</span></td></tr>)}{!payments.data.length&&<tr><td colSpan="7" className="text-center opacity-60">No supplier payments recorded.</td></tr>}</tbody></table></div>
  </div>;
};
export default SupplierPayments;
